version: 2
updates:
  - package-ecosystem: bun
    open-pull-requests-limit: 10
    directory: /
    commit-message:
      prefix: build
      prefix-development: chore
      include: scope
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    open-pull-requests-limit: 10
    directory: /
    commit-message:
      prefix: ci
    schedule:
      interval: weekly
