# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Linting, Testing and Auto-merge

on: pull_request_target

env:
  CI: true

jobs:
  lint_test_build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v4

      - name: Use Bun.sh
        uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun install

      - name: Lint code
        run: bun run lint

      - name: Test code
        run: bun run test
  auto-merge:
    needs: lint_test_build
    timeout-minutes: 5

    runs-on: ubuntu-22.04
    if: github.actor == 'dependabot[bot]'

    steps:
      - uses: actions/checkout@v4
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          approve: true
          github-token: ${{ secrets.GH_TOKEN }}
